<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArduPilot\XagSurveillanceGCS.ArduPilot.csproj" />
    <ProjectReference Include="..\Comms\XagSurveillanceGCS.Comms.csproj" />
    <ProjectReference Include="..\Controls\XagSurveillanceGCS.Controls.csproj" />
    <ProjectReference Include="..\Mavlink\MAVLink.csproj" />
    <ProjectReference Include="..\px4uploader\px4uploader.csproj" />
  </ItemGroup>

</Project>
